### ISSUE TITLE
Specify version of imported module  

### ISSUE THREAD

**Issue by elcamlost** [preaction/Import-Base#25]
Hi!

Maybe I missed something, but I can't find way to specify module version inside IMPORT_MODULES. 
I need something equivalent to ```use MODULE vX.X.X;```

Any plans for that?

Import::Into has support for version modules, so I think such goal is possible to achieve.

**Comment by preaction** [comment]
It sounds like something that should be done, but it might take a bit to get the syntax right.

Import::Into uses a hashref to allow that feature. That's certainly a possibility, we don't currently use a hashref in the args syntax. I'm not sure I like what that looks like though:

```
our @IMPORT_MODULES = (
    qw( strict warnings ),
    feature => [qw( :5.20 )],
    # Import::Into $target hashref
    { module => "MyModule", version => v1.2.3 } => [qw( foo bar baz )],
);
```

Perhaps a prettier way of doing it looks like:

```
our @IMPORT_MODULES = (
    qw( strict warnings ),
    feature => [qw( :5.20 )],
    # Hashref of Module name => Version number
    { MyModule => v1.2.3 } => [qw( foo bar baz )],
);
```

I believe vstrings/version objects can be detected, so we might in theory be able to also allow:

```
our @IMPORT_MODULES = (
    qw( strict warnings ),
    feature => [qw( :5.20 )],
    # Module name => version object => imports
    MyModule => v1.2.3 => [qw( foo bar baz )],
);
```

I'm unclear about the status of version objects though. I've heard conflicting stories about them...

In the end, it boils down to calling `MODULE->VERSION( vX.X.X );`, so temporarily while we bike-shed the details, you could try adding `"MODULE", sub { MODULE->VERSION( vX.X.X ); return }` to your list of things to import.

**Comment by elcamlost** [comment]
Great thanks. Last approach with anonymous function to check version is working.

**Comment by preaction** [comment]
Right. The rest of those are just examples of something that could be developed. If you're interesting in trying to implement one, I'll accept a PR. If not, I'll probably reserve some time in the next couple weeks to give them a try and see which one I like.

**Comment by preaction** [comment]
I've added the hashref `{ MODULE => VERSION }` syntax, but right now there's a bug in Import::Into (https://rt.cpan.org/Ticket/Display.html?id=106659) causing it to not work.

**Comment by elcamlost** [comment]
Greate Thanks!
